#!/usr/bin/env bash

# Handles all build steps on the jenkins instance
# all jenkins should do is call this file.
# NOTE: this script expects to be called from the root of the project, NOT from the build_scripts folder


cd poker.ui/
npm install
tsc
cd ..
cd poker.engine/
npm i
tsc
cd ..
npm run jenkins-artifact
